# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. Instalar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 2. Instalar pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9 # O la versión que uses localmente

      # 3. Instalar las dependencias de tu proyecto
      - name: Install dependencies
        run: pnpm install

      # 4. Compilar el proyecto de Vite inyectando la ruta base de GitHub Pages
      - name: Build project
        run: pnpm build -- --base=/tessy/

      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 5. Subir el artefacto (IMPORTANTE: Cambiamos '.' por 'dist')
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

      # 6. Desplegar en GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
